version: '2'
services:
  locust:
    image: fredriklack/docker-locust
    ports:
      - "8089:8089"
    volumes:
      - ./devops/locust:/locust
    command: locust -H http://web:3000
  redis:
    image: redis:latest
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - REDIS_URI=redis:6379
    volumes:
      - ${HOME}/go:/go
    ports:
      - "3000:3000"
    depends_on:
      - redis
